apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: dpu-operator
    app.kubernetes.io/part-of: dpu-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  template:
    spec:
      containers:
      - command:
        name: manager
        env:
        - name: DPU_DAEMON_IMAGE
          value: {{ .RegistryURL }}/dpu-daemon:dev
        - name: IntelVspImage
          value: {{ .RegistryURL }}/intel-vsp:dev
        - name: IntelVspP4Image
          value: {{ .RegistryURL }}/intel-vsp-p4:dev
        - name: MarvellVspImage
          value: {{ .RegistryURL }}/mrvl-vsp:dev
        - name: IMAGE_PULL_POLICIES
          value: Always
        - name: NETWORK_RESOURCES_INJECTOR_IMAGE
          value: {{ .RegistryURL }}/network-resources-injector:dev
        image: {{ .RegistryURL }}/dpu-operator:dev
        imagePullPolicy: Always
